# 全局信息
title: "博久游戏-红黑"

# 开发dev  测试test 上线 pro
active: dev
ser:
  protocol: "grpc"
  ip: "127.0.0.1"
  port: 17910
  etcdServer: ["127.0.0.1:2379"]
  regKey: "gameServer/hashrocket"
log:
  path: "./logs"
  prefix: "hashrocket"   # 日志文件前缀
  level: "debug"    # 日志级别：debug/info/error/warn
  development: true  # 是否为开发者模式
  debugFileSuffix: "debug.log"  # debug日志文件后缀
  warnFileSuffix: "warn.log"    # warn日志文件后缀
  errorFileSuffix: "error.log"   # error日志文件后缀
  infoFileSuffix: "info.log"    # info日志文件后缀
  maxAge: 2        # 保存的最大天数
  maxBackups: 30  # 最多存在多少个切片文件
  maxSize: 1  # 日日志文件大小（M）
mysql-master:
  addr: "127.0.0.1"
  port: 3306
  username: "root"
  password: "123456"
  database: "bj_rocket"
mysql-slave1:
  addr: "127.0.0.1"
  port: 3306
  username: "root"
  password: "123456"
  database: "bj_rocket"
redis:
  addr: "127.0.0.1:6379"
  password: ""
  DB: 0
  poolSize: 30
  minIdleConns: 30